'use strict';

let options = {};
if (process.env.NODE_ENV === 'production') {
  options.schema = process.env.SCHEMA;  // define your schema in options object
}

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    options.tableName = "Spots";
    return queryInterface.bulkInsert(options, [
      {
        ownerId: 1,
        address: "2034 Joshua Tree Road",
        city: "Joshua Tree",
        state: "California",
        country: "United States",
        lat: 33.8734,
        lng: -115.9010,
        name: "Invisible House",
        description: "An exploration in contrasts, the mirrored 22-story horizontal skyscraper features an entirely reflective facade that absorbs its surroundings and vanishes into the desert landscape.",
        price: 3652,
        category: "Camping",
        guests: 8,
        bedrooms: 4,
        beds: 4,
        bathrooms: 5,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: false
      },
      {
        ownerId: 2,
        address: "1234 Bodega Bay Street",
        city: "Bodega Bay",
        state: "California",
        country: "United States",
        lat: 38.3332,
        lng: -123.0481,
        name: "The Beach House",
        description: "This stunning house sits on a bluff directly above the ocean. Sit in the living room with a 180 degree view of the ocean, hear the waves as they roll in, watch birds of prey land on a cypress tree, and deer, foxes and other wildlife forage on the hill.",
        price: 600,
        category: "Beach",
        guests: 6,
        bedrooms: 3,
        beds: 3,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 3,
        address: "4321 Neskowin Drive",
        city: "Neskowin",
        state: "Oregon",
        country: "United States",
        lat: 45.1068,
        lng: -123.9843,
        name: "Neskape Beach House",
        description: "Our coastal home is a sophisticated blend of comfort and beautiful simplicity. With impeccable panoramic ocean views to enjoy.",
        price: 1034,
        category: "Beach",
        guests: 10,
        bedrooms: 8,
        beds: 8,
        bathrooms: 4,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 4,
        address: "3455 La Jolla Road",
        city: "San Diego",
        state: "California",
        country: "United States",
        lat: 32.8328,
        lng: -117.2713,
        name: "Luxury Listing w/ Exclusive View in La Jolla",
        description: "Come enjoy this beautiful home with amazing views and lots of entertainment just steps away!",
        price: 392,
        category: "Beach",
        guests: 4,
        bedrooms: 1,
        beds: 2,
        bathrooms: 1,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 5,
        address: "8347 Mission Beach Street",
        city: "San Diego",
        state: "California",
        country: "United States",
        lat: 32.7707,
        lng: -117.2514,
        name: "Oceanfront Condo w/ Private Roof Deck & Upgrades",
        description: "Wake up every day in paradise with panoramic ocean views you will never forget. ",
        price: 465,
        category: "Beach",
        guests: 4,
        bedrooms: 2,
        beds: 3,
        bathrooms: 3,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 6,
        address: "934 Inverness Drive",
        city: "Point Reyes Station",
        state: "California",
        country: "United States",
        lat: 38.0512,
        lng: -122.8663,
        name: "Inverness A-Frame",
        description: "Bohemian Modern A- Frame two bed two bath spacious cabin located in Northern California in beautiful West Marin county.",
        price: 586,
        category: "Cabin",
        guests: 6,
        bedrooms: 2,
        beds: 4,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 7,
        address: "259 Sea Ranch Lane",
        city: "Sea Ranch",
        state: "California",
        country: "United States",
        lat: 38.7152,
        lng: -123.4545,
        name: "Dog-Friendly Oceanfront Home with Gorgeous Views",
        description: "The Stoney home is a private oasis nestled atop the ocean bluff, with floor to ceiling windows offering panoramic views out over the ocean and the California coast.",
        price: 358,
        category: "Beach",
        guests: 8,
        bedrooms: 3,
        beds: 4,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 8,
        address: "6890 Temecula Lane",
        city: "Temecula",
        state: "California",
        country: "United States",
        lat: 33.4934,
        lng: -117.1488,
        name: "Ultimate Winery Getaway with Spa and Amazing Hilltop View",
        description: "Temecula Wine Country offers a wide array of  bucket-list worthy activities for those looking to retreat from the city.",
        price: 300,
        category: "Vineyard",
        guests: 13,
        bedrooms: 5,
        beds: 8,
        bathrooms: 3,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 1,
        address: "950 South Lake Tahoe Drive",
        city: "South Lake Tahoe",
        state: "California",
        country: "United States",
        lat: 38.9399,
        lng: -119.9772,
        name: "Huge Comfy Beautiful Log Cabin 7bdrms HotTub/Sauna",
        description: "This unique property is an enormous 7 bedroom log cabin minutes from beautiful Lake Tahoe. Relax on the large 700 sq. ft. deck w/ beautiful view, top of the line Hot Tub firepit outdoor sectional 6 person Barrel Sauna. Entertainment for everyone; pool table w/ bar, foosball,ping pong,basketball,Pac-Man. Trails right next to house for mountain hiking/biking etc. Located in a quiet neighborhood that is perfect for a relaxing mountain vacation/ corporate retreat.",
        price: 800,
        category: "Cabin",
        guests: 15,
        bedrooms: 7,
        beds: 11,
        bathrooms: 3,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 2,
        address: "329 Moonridge Road",
        city: "Big Bear",
        state: "California",
        country: "United States",
        lat: 34.2353,
        lng: -116.8556,
        name: "Cozy Cabin in the heart of Moonridge",
        description: "Beautiful Family style Cabin in the heart of Moonridge! Steps away from the slopes and village. Enjoy time by the fire with views for days. Our 3 bedroom home features a generously sized master bedroom and master bathroom, two guest rooms, full guest bath, full kitchen and dining area. 7 minutes from slopes, grocery stores and lake, our private cabin is perfect for those who want to get the full Big Bear experience",
        price: 320,
        category: "Cabin",
        guests: 6,
        bedrooms: 3,
        beds: 3,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 3,
        address: "829 Emigrant Lane",
        city: "Emigrant",
        state: "Montana",
        country: "United States",
        lat: 45.3686,
        lng: -110.7350,
        name: "Carbella Cabin - Over 70 Acres Overlooking Tom Min",
        description: "Over 70 Acres Overlooking Tom Miner Basin. This charming two-bedroom, two-bath cabin is perched on a hillside just miles from Yellowstone National Park. It offers spectacular views of the Yellowstone River valley and the surrounding mountains. The property consists of over 70 acres, offering private hiking trails right out your front door. For those fond of fishing, grab your rod and head down to the Yellowstone River, as public access is within walking distance from the home.",
        price: 304,
        category: "Cabin",
        guests: 5,
        bedrooms: 2,
        beds: 3,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 4,
        address: "238 Dresden Court",
        city: "Dresden",
        state: "Maine",
        country: "United States",
        lat: 44.1071,
        lng: -69.7242,
        name: "Waterfront Dresden Cabin with Deck + Fire Pit!",
        description: "Wake up to the sweet smell of fresh coffee and stunning Kennebec River views when you book this immaculate Dresden vacation rental! Located just a few steps from the water, this 2-bedroom, 1.5-bathroom cabin is ideal for outdoor enthusiasts and families looking for some R ‘n R. The home features a full kitchen, a Smart TV, free WiFi, and 1,400 square feet of stylish living space. Bring your kayaks and paddleboards for on-the-water fun, then gather around the fire pit for tasty s'mores! Book now.",
        price: 251,
        category: "Cabin",
        guests: 6,
        bedrooms: 2,
        beds: 4,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 5,
        address: "521 Bremerton Heights",
        city: "Bremerton",
        state: "Washington",
        country: "United States",
        lat: 47.5650,
        lng: -122.6270,
        name: "The Rockland Woods Lodge, Lake & Land",
        description: "The Rockland Woods Lodge was originally built in 1973 and a 2018 rustic-modern remodel freshened up its charm. A relaxing 60-min Ferry Ride from Seattle gets you to a quiet, densely wooded 20-acre property overlooking Mission Lake and the Olympic Mtns. Biannually, we host 10-20 Artists-in-Residence at the property without charge. To support this primary mission, we rent to small groups for retreats, reunions, workshops, and weddings. Thanks for supporting Artists with your rental!",
        price: 424,
        category: "Camping",
        guests: 13,
        bedrooms: 6,
        beds: 12,
        bathrooms: 3,
        wifi: false,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 6,
        address: "629 Therm Road",
        city: "Thermopolis",
        state: "Wyoming",
        country: "United States",
        lat: 43.6461,
        lng: -108.2120,
        name: "Tipi 7 w/Day Pass for Hot Springs",
        description: "Glamping, the term used for upscale, glamorous camping is one of the fastest growing trends in the hospitality industry. Glamour camping offers the wilderness access & fresh air of camping, but filled with lush & comfortable amenities! We are conveniently located 5 miles from Thermopolis, Hot Springs State Park, & overlooking the Wind River meeting the Big Horn River!",
        price: 167,
        category: "Camping",
        guests: 6,
        bedrooms: 1,
        beds: 3,
        bathrooms: 2,
        wifi: false,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 7,
        address: "304 Alberton Street",
        city: "Alberton",
        state: "Montana",
        country: "United States",
        lat: 47.0016,
        lng: -114.4735,
        name: "Vintage Airstream with Fabulous Views",
        description: "This 28-foot 1963 Airstream Ambassador named 'Tammy' is clean with comfortable amenities. Located on our food and flower farm - Crescent Ridge Farm, the Airstream is in a private area and offers views of the river and our majestic valley. There is a private yard for you with shade trees, chiminea and a patio. While visiting, enjoy a stroll through the one acre flower and vegetable garden, walk the road viewing the river, or simply sit back and watch the wildlife pass you by.",
        price: 89,
        category: "Camping",
        guests: 4,
        bedrooms: 1,
        beds: 2,
        bathrooms: 1,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 8,
        address: "156 Newbury Road",
        city: "Newbury",
        state: "New Hampshire",
        country: "United States",
        lat: 43.3215,
        lng: -72.0359,
        name: "Four Season Historic Chalet / Sleeps 22+ / Sunapee",
        description: "The Stone Barn at Well Sweep is an historical property three min to Lake Sunapee. Six min to Mt. Sunapee. With 7 bedrooms + 5.5 baths, the 7000 sq ft barn has beds for 12 kids+10 adults; also has a crib, futon, pack-n-plays, and toddler cots. Views of Mt. Sunapee. Double-sided fireplace and soaring ceiling in great room and kitchen. Large Rec/TV room with bar. Wifi. Office. Massive lawns for outdoor activities. 10 car parking; garage for 1. Discounts for wk/mo rentals. Ski, hike, swim, boat!",
        price: 707,
        category: "Countryside",
        guests: 15,
        bedrooms: 7,
        beds: 10,
        bathrooms: 5,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 1,
        address: "803 Tuscon Lane",
        city: "Tuscon",
        state: "Arizona",
        country: "United States",
        lat: 32.2540,
        lng: -110.9742,
        name: "Desert Retreat with Private Pool",
        description: "This 14 acre desert retreat offers a cozy rustic home with a private pool, king bed, spacious living area and breathtaking views. Nestled near hiking trails and a golf club, it's the perfect blend of seclusion and adventure. Only 15 minutes from downtown and with free parking and private entrance, it's the ultimate cozy getaway.",
        price: 354,
        category: "Desert",
        guests: 6,
        bedrooms: 3,
        beds: 3,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 2,
        address: "29 Palms Desert",
        city: "Twentynine Palms",
        state: "California",
        country: "United States",
        lat: 34.1356,
        lng: -116.0542,
        name: "Ultimate Desert Getaway. Views. Casa De Sunset",
        description: "You came to the right place! This home has everything a family would want with outdoor entertainment and space. Even perfect for couples wanting to take a step back & reconnect next to a cozy fire with a bottle of wine. Whether with a bigger party or just a couple’s getaway this is home for you! Sitting on 5 acres you have the best of both world- no neighboring homes within in a mile, but just 15 min from JTNP & 7 min from town stores and restaurants. Pets welcome. UNLIMITED FIRE WOOD. EV-plug",
        price: 113,
        category: "Desert",
        guests: 8,
        bedrooms: 2,
        beds: 4,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 3,
        address: "9183 El Paso Street",
        city: "El Paso",
        state: "Texas",
        country: "United States",
        lat: 31.7619,
        lng: -106.4850,
        name: "Central El Paso Unit #2 Red Door Studio w Mtn View",
        description: "This absolutely charming 2 BR/ 1 BA home in the heart of central El Paso is awaiting your arrival. You will be comfortable with the full use of high speed WIFI and smart tv . Keep your space heated and cooled to your liking with a fully controllable split system unit. Within walking distance you can enjoy great food and great scenery. 10 minutes from the airport, with Easy access to FORT BLISS, UTEP, Hospitals near by and the MOUNTAINS!! Enjoy our home!",
        price: 50,
        category: "Desert",
        guests: 2,
        bedrooms: 1,
        beds: 1,
        bathrooms: 1,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 4,
        address: "2094 Barnstead Road",
        city: "Barnstead",
        state: "New Hampshire",
        country: "United States",
        lat: 43.3389,
        lng: -71.2782,
        name: "Lakefront home /3BR 2BA/ Dock/ Game room/ Garage",
        description: "Want that 'Ahh' feeling that only comes from a real lake vacation? This home offers scenic views of the lake from most rooms; the expansive deck is a few feet from water's edge. With a 5-burner grill it's a great place for a family meal. Kids will love playing with water toys on the sandy beach, taking a dip in the lake; fishing or launching a kayak or paddle board from the private dock. Time to go back in? There's more to enjoy: ping-pong, darts, board games, streaming your favorite shows.",
        price: 270,
        category: "Lake",
        guests: 7,
        bedrooms: 3,
        beds: 4,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 5,
        address: "5792 Oostburg Lane",
        city: "Oostburg",
        state: "Wisconsin",
        country: "United States",
        lat: 43.6228,
        lng: -87.7945,
        name: "Lake House w/ 6-BR's near Kohler-Andrae/Sheboygan",
        description: "Escape to the serene beauty of this stunning lakefront vacation rental, situated right on Lake Michigan and just moments away from Kohler, Sheboygan, and Kohler-Andrae State Park. Nestled on a tranquil waterfront setting, this property boasts spectacular views, a private beach, and the peace and quiet you've been searching for.",
        price: 450,
        category: "Lake",
        guests: 14,
        bedrooms: 6,
        beds: 8,
        bathrooms: 4,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 6,
        address: "3201 Lake Cushman Road",
        city: "Hoodsport",
        state: "Washington",
        country: "United States",
        lat: 47.4064,
        lng: -123.1406,
        name: "Olympic National Park 3 bed/2 bath W/Stunning Lake View",
        description: "Welcome to Potlatch Cabin! The cabin is perched in the trees over the shores of Lake Cushman with expansive views of the lake and mountains of the Olympics. It features newly remodelled spaces and is the perfect destination for relaxing by a fire, watching sunset on the deck, or playing a competitive match of foosball in the game room. The house is 15 mins from the Staircase entrance to Olympic National Park and 20 mins to Hoodsport and Hood canal. Strictly no pets/parties. A gem in the woods!",
        price: 261,
        category: "National Parks",
        guests: 8,
        bedrooms: 3,
        beds: 4,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 7,
        address: "4918 Rainier Drive",
        city: "Ashford",
        state: "Washington",
        country: "United States",
        lat: 46.7584,
        lng: -122.0309,
        name: "Mt. Rainer National Park Cozy family getaway, kids & pet friendly!",
        description: "Welcome to Potlatch Cabin! The cabin is perched in the trees over the shores of Lake Cushman with expansive views of the lake and mountains of the Olympics. It features newly remodelled spaces and is the perfect destination for relaxing by a fire, watching sunset on the deck, or playing a competitive match of foosball in the game room. The house is 15 mins from the Staircase entrance to Olympic National Park and 20 mins to Hoodsport and Hood canal. Strictly no pets/parties. A gem in the woods!",
        price: 148,
        category: "National Parks",
        guests: 8,
        bedrooms: 3,
        beds: 5,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 8,
        address: "220 Rocky Road",
        city: "Lyons",
        state: "Colorado",
        country: "United States",
        lat: 40.2247,
        lng: -105.2714,
        name: "Little Red Treehouse",
        description: "Open May 1 2019 . The Little Red Tree house accommodates two guests only. It has huge views, private shower, with separate powder room sink and toilet. It has an efficiency kitchen, with small sink and counter top,as well as a fridge. The tree house is equipped with heat/air and electricity. Located on the way to Rocky Mountain NP, directly across from Rocky Grass There is a full size pull down Murphy bed which sleeps two , the fairy loft sleeps one.Total occupancy two people maximum !",
        price: 250,
        category: "National Parks",
        guests: 2,
        bedrooms: 1,
        beds: 2,
        bathrooms: 1,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 1,
        address: "720 New York Lane",
        city: "New York",
        state: "New York",
        country: "United States",
        lat: 40.7128,
        lng: -74.0060,
        name: "Amazing 2bed's / stunning views to Empire State",
        description: "Amazing apartment with stunning skyline views to Manhattan and the Empire State. don't look further if you need a quick access  to to Hudson Yards, Time Square, Hell's Kitchen, Javits Center, the Summit Vanderbilt , Bryant Park, The Vessel and many more",
        price: 950,
        category: "Iconic cities",
        guests: 4,
        bedrooms: 2,
        beds: 2,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: false,
        washer: true,
        dryer: true
      },
      {
        ownerId: 2,
        address: "577 Nashville Drive",
        city: "Nashville",
        state: "Tennessee",
        country: "United States",
        lat: 36.1627,
        lng: -86.7816,
        name: "The Sunset Home! Free Parking, Mins To Broadway!",
        description: "Welcome to Music City!!! This property is a beautiful 3 story townhome located just minutes from center of downtown Nashville. With the high end interior finish, the comfortable layout and the 3rd story deck with a view of downtown this property will allow you to experience Nashville to the fullest.",
        price: 1030,
        category: "Iconic cities",
        guests: 8,
        bedrooms: 2,
        beds: 4,
        bathrooms: 3,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 3,
        address: "347 Manhattan Lane",
        city: "New York",
        state: "New York",
        country: "United States",
        lat: 40.7831,
        lng: -73.9712,
        name: "Secret Carriage House",
        description: "A hidden 19th century carriage house gem, out of sight and away from the noise, re-invented for modern New York living. Three floors of private living space includes an open plan dining-kitchen and living level, two upstairs bedrooms , a home office / screening room lower level with sleeping sofa option, three full bathrooms, two-person sauna, large walled garden, well-equipped cooking kitchen, under-floor heating, central AC, high speed internet, a collection of contemporary art, and more.",
        price: 749,
        category: "Iconic cities",
        guests: 5,
        bedrooms: 2,
        beds: 3,
        bathrooms: 3,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
      {
        ownerId: 4,
        address: "610 Boston Road",
        city: "Boston",
        state: "Massachusetts",
        country: "United States",
        lat: 42.3555,
        lng: -71.0565,
        name: "Fully Furnished 4br, 2ba Flat!",
        description: "This 4 Bed, 2 Bath beautifully furnished apartment with Laundry in unit, and fully equipped kitchen available for both long and short term rental. With one King bed and 3 Queens, this beautifully designed and furnished loft is located right in downtown Boston. Includes all furnishings and cooking equipment! The apartment is accessible via a self-check-in process to lower your exposure! Security on-site, and 2 Elevators. Units are professionally cleaned and disinfected between every stay.",
        price: 684,
        category: "Iconic cities",
        guests: 7,
        bedrooms: 4,
        beds: 4,
        bathrooms: 2,
        wifi: true,
        parking: true,
        kitchen: true,
        pets: true,
        washer: true,
        dryer: true
      },
    ], {})
  },

  async down(queryInterface, Sequelize) {
    options.tableName = "Spots";
    const Op = Sequelize.Op;
    return queryInterface.bulkDelete(options, {
      id: { [Op.in]: [1, 2, 3, 4, 5, 6, 7, 8] }
    }, {});
  }
};
