'use strict';

let options = {};
if (process.env.NODE_ENV === 'production') {
  options.schema = process.env.SCHEMA;  // define your schema in options object
}

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    options.tableName = "Reviews";
    return queryInterface.bulkInsert(options, [
      {
        spotId: 1,
        userId: 2,
        review: "So modern and minimalistic!",
        cleanliness: 5,
        communication: 5,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 1,
        userId: 3,
        review: "The view from the balcony was breathtaking, and the apartment was very comfortable.",
        cleanliness: 4,
        communication: 5,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 5,
      },
      {
        spotId: 1,
        userId: 4,
        review: "Great location with a stunning view. The host was very helpful.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 1,
        userId: 5,
        review: "A fantastic stay in a beautiful apartment with amazing views.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 1,
        userId: 6,
        review: "The host was very responsive and provided excellent recommendations.",
        cleanliness: 5,
        communication: 5,
        checkin: 1,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 1,
        userId: 7,
        review: "Loved our stay! The apartment was clean, comfortable, and in a great location.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 1,
        userId: 8,
        review: "Incredible architecture in the desert! Truly felt invisible.",
        cleanliness: 4,
        communication: 5,
        checkin: 3,
        accuracy: 5,
        location: 4,
        value: 4,
      },
      {
        spotId: 2,
        userId: 1,
        review: "Breathtaking ocean view, and loved the cozy atmosphere.",
        cleanliness: 5,
        communication: 4,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 2,
        userId: 3,
        review: "Fantastic view of the ocean with an inviting vibe",
        cleanliness: 5,
        communication: 4,
        checkin: 2,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 2,
        userId: 4,
        review: "The home had a warm and inviting atmosphere, perfect for a family gathering.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 2,
        userId: 5,
        review: "The house was spacious, well-equipped, and the backyard was perfect for our kids.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 2,
        userId: 6,
        review: "The house was cozy and clean, and the backyard was an added bonus.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 2,
        userId: 7,
        review: "A lovely home in a quiet neighborhood. We enjoyed our stay.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 3,
        userId: 1,
        review: "Such a great time!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 3,
        userId: 2,
        review: "Neskape Beach House offered stunning views and great comfort.",
        cleanliness: 4,
        communication: 5,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 3,
        userId: 4,
        review: "A cozy and clean cabin with all the amenities needed for a perfect weekend getaway.",
        cleanliness: 5,
        communication: 2,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 3,
        userId: 5,
        review: "Beautiful cabin in a serene location. We loved our stay.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 3,
        userId: 6,
        review: "A fantastic cabin getaway. The host was very attentive and helpful.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 3,
        userId: 7,
        review: "We enjoyed our stay at this lovely cabin. It had everything we needed for a relaxing trip.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 3,
        userId: 8,
        review: "The cabin was clean, comfortable, and in a great location. Highly recommend!",
        cleanliness: 3,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 4,
        userId: 1,
        review: "Highly recommend!",
        cleanliness: 4,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 4,
        userId: 2,
        review: "The room was clean and cozy. The shared spaces were well-kept.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 4,
        value: 4,
      },
      {
        spotId: 4,
        userId: 3,
        review: "Affordable and convenient place to stay. The host was friendly and accommodating.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 4,
        value: 3
      },
      {
        spotId: 4,
        userId: 5,
        review: "A comfortable stay in a convenient location. The host was very helpful.",
        cleanliness: 5,
        communication: 5,
        checkin: 2,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 4,
        userId: 6,
        review: "Great value for the price. Clean room and easy access to public transportation.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 5,
      },
      {
        spotId: 4,
        userId: 7,
        review: "A budget-friendly stay with a hospitable host. The location was quite convenient.",
        cleanliness: 4,
        communication: 5,
        checkin: 5,
        accuracy: 4,
        location: 4,
        value: 5,
      },
      {
        spotId: 4,
        userId: 8,
        review: "Clean and cozy room, ideal for a short stay. The host was very kind and welcoming.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 4,
        value: 5,
      },
      {
        spotId: 5,
        userId: 1,
        review: "Beautiful deck views!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 5,
        userId: 2,
        review: "A beautiful beachfront property with stunning views. The house was clean and well-equipped.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 5,
        userId: 3,
        review: "The beach house was perfect for our family vacation. We loved the proximity to the beach.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 5,
        userId: 4,
        review: "We had a great time at this beachfront property. The house was clean, spacious, and comfortable.",
        cleanliness: 2,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 5,
        userId: 6,
        review: "An amazing location with incredible beach views. We thoroughly enjoyed our stay.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 5,
        userId: 7,
        review: "The beach house was perfect for a relaxing getaway. The views were stunning, and the house was well-equipped.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 5,
        userId: 8,
        review: "A fantastic beachfront property with all the amenities needed for a perfect vacation. Highly recommended!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 6,
        userId: 7,
        review: "Cozy cabin in nature!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 7,
        userId: 8,
        review: "Great spot in Sea Ranch!",
        cleanliness: 5,
        communication: 2,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 8,
        userId: 1,
        review: "Perfect for wine expeditions!",
        cleanliness: 5,
        communication: 4,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 4,
        userId: 4,
        review: "Luxury in La Jolla with amazing views and nearby entertainment.",
        cleanliness: 5,
        communication: 3,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 5,
        userId: 5,
        review: "Incredible oceanfront views and enjoyed the private roof deck!",
        cleanliness: 4,
        communication: 4,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 6,
        userId: 1,
        review: "Inverness A-Frame is a stylish and spacious cabin in a beautiful setting.",
        cleanliness: 5,
        communication: 5,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 6,
        userId: 2,
        review: "A charming cottage with a lovely garden. The host was friendly and helpful.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 6,
        userId: 3,
        review: "The cottage was cozy and well-maintained, perfect for a romantic getaway.",
        cleanliness: 5,
        communication: 5,
        checkin: 3,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 6,
        userId: 4,
        review: "A delightful stay in a charming cottage. The garden was a wonderful place to relax.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 6,
        userId: 5,
        review: "We enjoyed our stay at this quaint cottage. The host was very attentive and helpful.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 6,
        userId: 7,
        review: "A lovely cottage experience with a beautiful garden. The host was welcoming and responsive.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 6,
        userId: 8,
        review: "The cottage was cozy and clean, with a lovely garden to enjoy. The host was very accommodating.",
        cleanliness: 5,
        communication: 2,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 7,
        userId: 1,
        review: "Dog-friendly oceanfront home with absolutely stunning views.",
        cleanliness: 5,
        communication: 3,
        checkin: 5,
        accuracy: 5,
        location: 4,
        value: 4,
      },
      {
        spotId: 7,
        userId: 2,
        review: "The loft was stylish and well-equipped. The location was perfect for exploring the city.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 7,
        userId: 3,
        review: "A beautiful and spacious loft in a great location. The host was very helpful.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 7,
        userId: 4,
        review: "The loft was spacious and beautifully decorated. We enjoyed the central location.",
        cleanliness: 5,
        communication: 2,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 7,
        userId: 5,
        review: "A stylish and comfortable loft in a fantastic location. The host was very responsive.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 7,
        userId: 6,
        review: "We had a great time at this trendy loft. The location was perfect, and the space was very comfortable.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 7,
        userId: 8,
        review: "The loft was clean, spacious, and well-located. We had an enjoyable stay.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 8,
        userId: 2,
        review: "Perfect winery getaway with amazing hilltop view and relaxing spa.",
        cleanliness: 4,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 4,
        value: 5,
      },
      {
        spotId: 8,
        userId: 3,
        review: "The villa was stunning, with beautiful views and a fantastic pool area.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 8,
        userId: 4,
        review: "An amazing villa with breathtaking views. The pool area was perfect for relaxing.",
        cleanliness: 5,
        communication: 5,
        checkin: 2,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 8,
        userId: 5,
        review: "We had a wonderful time at this luxurious villa. The views and pool area were exceptional.",
        cleanliness: 5,
        communication: 1,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 8,
        userId: 6,
        review: "An incredible villa with stunning views and top-notch amenities. We loved our stay.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 8,
        userId: 7,
        review: "The villa was beautiful and well-maintained, with amazing views and a fantastic pool.",
        cleanliness: 5,
        communication: 1,
        checkin: 5,
        accuracy: 3,
        location: 5,
        value: 5,
      },
      {
        spotId: 8,
        userId: 1,
        review: "The villa exceeded our expectations with its stunning views and luxurious amenities. The pool area was perfect for relaxation.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 9,
        userId: 3,
        review: "Beautiful log cabin with fun amenities, perfect for a group retreat.",
        cleanliness: 5,
        communication: 4,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 9,
        userId: 4,
        review: "A clean and comfortable apartment with a great view of the city. The host was very helpful.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 9,
        userId: 5,
        review: "The apartment was cozy and well-located, with a fantastic view. We had a great stay.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 9,
        userId: 6,
        review: "We loved the central location and the stunning view from the apartment. The host was very accommodating.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 9,
        userId: 7,
        review: "A wonderful apartment with a great view of the city. The location was ideal for exploring the area.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 9,
        userId: 8,
        review: "The apartment was clean, comfortable, and well-situated. We enjoyed the beautiful view of the city.",
        cleanliness: 5,
        communication: 5,
        checkin: 3,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 9,
        userId: 1,
        review: "A lovely apartment with an amazing view. The location was perfect for exploring the city.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 10,
        userId: 2,
        review: "Cozy cabin in Moonridge, perfect location for a Big Bear experience.",
        cleanliness: 4,
        communication: 5,
        checkin: 3,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 10,
        userId: 3,
        review: "The treehouse was a unique and enjoyable experience. The setting was peaceful and beautiful.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 10,
        userId: 4,
        review: "We had a memorable stay at this lovely treehouse. The surrounding nature was breathtaking.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 2,
        location: 5,
        value: 5,
      },
      {
        spotId: 10,
        userId: 5,
        review: "The treehouse was a truly unique and magical experience. We loved being surrounded by nature.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 3,
        location: 5,
        value: 5,
      },
      {
        spotId: 10,
        userId: 6,
        review: "A wonderful getaway in this charming treehouse. The location was serene, and the treehouse was cozy.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 10,
        userId: 7,
        review: "Staying in this treehouse was an unforgettable experience. The peaceful setting and beautiful surroundings made our stay truly special.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 10,
        userId: 8,
        review: "The treehouse was a one-of-a-kind experience that we'll never forget. The location was tranquil, and the treehouse itself was well-designed and comfortable.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 11,
        userId: 1,
        review: "Carbella Cabin offers fantastic views and proximity to Yellowstone.",
        cleanliness: 5,
        communication: 4,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 11,
        userId: 2,
        review: "The cabin was cozy and well-equipped, with beautiful views of the mountains.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 11,
        userId: 3,
        review: "We had a relaxing stay at this mountain cabin. The views were incredible, and the cabin was comfortable.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 11,
        userId: 4,
        review: "A wonderful mountain retreat with stunning views. The cabin was clean and well-maintained.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 11,
        userId: 5,
        review: "We loved our stay at this beautiful mountain cabin. The views were breathtaking, and the cabin was cozy and well-equipped.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 11,
        userId: 6,
        review: "The cabin was the perfect mountain getaway. The views were amazing, and the cabin itself was very comfortable.",
        cleanliness: 5,
        communication: 3,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 11,
        userId: 7,
        review: "Our stay at the mountain cabin was unforgettable. The breathtaking views and cozy atmosphere made for a perfect retreat.",
        cleanliness: 5,
        communication: 2,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 12,
        userId: 1,
        review: "What a serene and delightful stay! The cabin was spacious and clean, with a stunning view of the river. Loved gathering around the fire pit at night!",
        cleanliness: 5,
        communication: 1,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 12,
        userId: 2,
        review: "The cabin was perfect for our family getaway. The deck and fire pit were amazing, and the location is great for exploring the surrounding area.",
        cleanliness: 4,
        communication: 5,
        checkin: 5,
        accuracy: 3,
        location: 5,
        value: 4,
      },
      {
        spotId: 12,
        userId: 3,
        review: "We had a relaxing weekend at the cabin, and the waterfront view was gorgeous. Everything we needed was available, and we enjoyed the fire pit in the evening.",
        cleanliness: 5,
        communication: 4,
        checkin: 5,
        accuracy: 4,
        location: 5,
        value: 5,
      },
      {
        spotId: 12,
        userId: 8,
        review: "The cabin is in an excellent location, and we loved waking up to the view of the river. The place was clean and well-equipped, making our stay comfortable.",
        cleanliness: 5,
        communication: 1,
        checkin: 5,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 12,
        userId: 5,
        review: "A fantastic stay at the waterfront cabin! The views were spectacular, and the cabin was well-maintained and cozy. The deck and fire pit were a great addition.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 12,
        userId: 6,
        review: "The cabin was perfect for our weekend getaway. The view of the river was breathtaking, and the cabin had everything we needed for a comfortable stay.",
        cleanliness: 4,
        communication: 2,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 12,
        userId: 7,
        review: "Our family loved our time at the cabin. The waterfront view was incredible, and the fire pit was perfect for evenings spent roasting marshmallows.",
        cleanliness: 5,
        communication: 5,
        checkin: 3,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 13,
        userId: 4,
        review: "The Rockland Woods Lodge is a true hidden gem! The property is stunning, and we loved the quiet and secluded location. It was a great place for our family reunion.",
        cleanliness: 5,
        communication: 5,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 13,
        userId: 2,
        review: "We had an amazing time at Rockland Woods Lodge. The location was perfect for our group retreat, with plenty of space for everyone. The views of Mission Lake were breathtaking!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 2,
        location: 5,
        value: 5,
      },
      {
        spotId: 13,
        userId: 3,
        review: "Our stay at the Rockland Woods Lodge was exceptional. The property was beautiful and well-maintained, and we truly appreciated the seclusion and tranquility it offered.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 13,
        userId: 1,
        review: "The lodge was an excellent choice for our family reunion. The rustic-modern design was charming, and the property offered ample space for outdoor activities.",
        cleanliness: 4,
        communication: 5,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 13,
        userId: 8,
        review: "We hosted our team-building retreat at Rockland Woods Lodge, and it was perfect! The property is gorgeous, and we loved the peaceful surroundings. Highly recommended!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 13,
        userId: 6,
        review: "Our stay at the lodge was unforgettable. The property is stunning, and we enjoyed exploring the area and taking in the beautiful views of Mission Lake.",
        cleanliness: 5,
        communication: 3,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 13,
        userId: 7,
        review: "The Rockland Woods Lodge was the perfect setting for our workshop. The property is beautiful and peaceful, and the rustic-modern design added a unique touch.",
        cleanliness: 5,
        communication: 5,
        checkin: 3,
        accuracy: 5,
        location: 4,
        value: 5,
      },
      {
        spotId: 14,
        userId: 5,
        review: "Glamping at its finest! The tipi was comfortable and well-equipped, and the location was simply stunning. We loved our day passes to the hot springs and can't wait to come back!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 14,
        userId: 2,
        review: "Our stay in Tipi 7 was an unforgettable experience. The beautiful scenery, combined with the comfort of the tipi and access to the hot springs, made for a perfect getaway.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 14,
        userId: 3,
        review: "The tipi was amazing, and the hot springs were a fantastic bonus. We appreciated the unique accommodations and the beautiful surroundings. Highly recommend!",
        cleanliness: 4,
        communication: 5,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 14,
        userId: 4,
        review: "We had a great time at Tipi 7. The accommodations were comfortable and well-maintained, and the hot springs were a fantastic way to unwind after a day of exploring the area.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 14,
        userId: 1,
        review: "This was such a unique and memorable experience! The tipi was cozy, and the hot springs were a wonderful addition. We loved the beautiful views and can't wait to return!",
        cleanliness: 5,
        communication: 2,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 14,
        userId: 8,
        review: "Our stay at Tipi 7 was a fantastic experience. The tipi was comfortable and well-equipped, and the hot springs provided a relaxing retreat. We'll definitely be back!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 14,
        userId: 7,
        review: "We loved our stay at Tipi 7! The accommodations were unique and comfortable, and the hot springs were a delightful treat. The scenery was beautiful, and we enjoyed every moment.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 15,
        userId: 1,
        review: "Tammy the Airstream was a charming and unique experience!",
        cleanliness: 5,
        communication: 4,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 15,
        userId: 2,
        review: "The farm setting and river view made our stay unforgettable.",
        cleanliness: 4,
        communication: 5,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 5,
      },
      {
        spotId: 15,
        userId: 3,
        review: "Loved the vintage charm and peaceful atmosphere.",
        cleanliness: 4,
        communication: 4,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 15,
        userId: 4,
        review: "Amazing stargazing and the farm-fresh vegetables were a bonus!",
        cleanliness: 5,
        communication: 5,
        checkin: 2,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 15,
        userId: 5,
        review: "A cozy retreat in a beautiful, tranquil setting.",
        cleanliness: 5,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 15,
        userId: 6,
        review: "Tammy is a gem, and the farm is a lovely escape from the city.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 15,
        userId: 7,
        review: "An idyllic glamping experience with all the comforts of home.",
        cleanliness: 4,
        communication: 4,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 16,
        userId: 7,
        review: "The Stone Barn was perfect for our large group. The historic charm combined with modern amenities made our stay comfortable and enjoyable. The location was convenient for skiing and other outdoor activities.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 16,
        userId: 2,
        review: "Our group had a fantastic stay at the Stone Barn. The space was large enough for everyone to spread out, and the amenities were perfect for our needs. The views of Mt. Sunapee were stunning, and the location was great for skiing and hiking.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 4,
        location: 5,
        value: 5,
      },
      {
        spotId: 16,
        userId: 3,
        review: "We had an amazing time at the Stone Barn. It was spacious, comfortable, and well-appointed. The location was perfect for outdoor activities, and the views were absolutely breathtaking. We would definitely stay here again!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 1,
        location: 5,
        value: 5,
      },
      {
        spotId: 16,
        userId: 4,
        review: "The Stone Barn was a fantastic choice for our family reunion. The space was large and comfortable, and the amenities were perfect for our needs. We especially loved the outdoor spaces and the incredible views of Mt. Sunapee.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 16,
        userId: 5,
        review: "Our group had a wonderful time at the Stone Barn. The historic charm, combined with modern amenities, made for a comfortable and enjoyable stay. The location was perfect for skiing, hiking, and other outdoor activities.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 4,
        value: 5,
      },
      {
        spotId: 16,
        userId: 6,
        review: "We had an amazing stay at the Stone Barn. The space was spacious, well-appointed, and perfect for our large group. The views of Mt. Sunapee were stunning, and the location was great for outdoor activities. We can't wait to return!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 16,
        userId: 1,
        review: "The Stone Barn was an excellent choice for our group getaway. The historic charm and modern amenities made it a comfortable and enjoyable stay. The views were incredible, and the location was perfect for skiing and other outdoor activities.",
        cleanliness: 5,
        communication: 2,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 17,
        userId: 8,
        review: "The desert retreat was a perfect getaway for our family. The private pool was amazing, and the views were breathtaking. The house was comfortable and well-equipped, making our stay very enjoyable.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 3,
      },
      {
        spotId: 17,
        userId: 2,
        review: "We had a fantastic time at this desert retreat! The private pool was perfect for relaxing and cooling off in the heat, and the views of the surrounding desert were stunning. The house itself was well-equipped and comfortable, making our stay a pleasure.",
        cleanliness: 5,
        communication: 5,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 17,
        userId: 3,
        review: "This desert retreat exceeded our expectations. The private pool was a fantastic addition, and the views of the desert landscape were absolutely breathtaking. The house was clean, comfortable, and had everything we needed for a great stay.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 4,
        location: 5,
        value: 5,
      },
      {
        spotId: 17,
        userId: 4,
        review: "We thoroughly enjoyed our stay at this desert retreat. The private pool was a highlight, and the views were incredible. The house was well-equipped and comfortable, making it the perfect place to relax and unwind after a day of exploring the area.",
        cleanliness: 5,
        communication: 1,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 17,
        userId: 5,
        review: "This desert retreat was the perfect getaway for us. The private pool was a major highlight, and the views of the surrounding desert were stunning. The house was clean, comfortable, and had everything we needed for a fantastic stay.",
        cleanliness: 5,
        communication: 4,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 17,
        userId: 6,
        review: "We loved our stay at this desert retreat. The private pool was amazing, and the views of the desert landscape were breathtaking. The house was well-equipped and comfortable, making our stay enjoyable and relaxing.",
        cleanliness: 3,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 17,
        userId: 7,
        review: "This desert retreat was a fantastic place to stay. The private pool was perfect for cooling off and relaxing, and the views of the desert were stunning. The house was clean, comfortable, and had everything we needed for a great vacation.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 4,
        location: 5,
        value: 5,
      },
      {
        spotId: 18,
        userId: 6,
        review: "Casa De Sunset was a wonderful desert getaway. The views were stunning, and the house was well-equipped and comfortable. We especially loved the outdoor space and the cozy fire pit. It was a great base for exploring Joshua Tree National Park.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 18,
        userId: 8,
        review: "Casa De Sunset was amazing. Breathtaking views, well-equipped, and comfortable. The outdoor space was perfect for star-gazing. Convenient location for visiting Joshua Tree National Park.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 18,
        userId: 3,
        review: "Fantastic desert getaway at Casa De Sunset. Incredible views, cozy house, and great outdoor space. Loved the fire pit and proximity to Joshua Tree National Park.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 18,
        userId: 4,
        review: "Wonderful stay at Casa De Sunset. Stunning desert views, comfortable house, and perfect outdoor space for star-gazing. Great base for exploring Joshua Tree National Park.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 18,
        userId: 5,
        review: "Loved Casa De Sunset. Amazing desert views, cozy house, and relaxing outdoor space. Conveniently located for visiting Joshua Tree National Park.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 18,
        userId: 1,
        review: "Fantastic desert retreat at Casa De Sunset. Breathtaking views, comfortable house, and great outdoor space with fire pit. Perfect for exploring Joshua Tree National Park.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 18,
        userId: 7,
        review: "Incredible stay at Casa De Sunset. Stunning desert views, well-equipped, and cozy. Outdoor space perfect for star-gazing. Close to Joshua Tree National Park.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 19,
        userId: 5,
        review: "We loved our stay at the Red Door Studio! Comfortable, clean, and centrally located. The mountain view was an added bonus. Highly recommend!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 19,
        userId: 2,
        review: "The Red Door Studio was perfect for our stay in El Paso. It was clean, cozy, and close to everything we needed. The mountain view was a treat!",
        cleanliness: 5,
        communication: 3,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 19,
        userId: 8,
        review: "Central El Paso Unit #2 Red Door Studio was a lovely, well-equipped space with a great mountain view. Easy access to attractions and amenities.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 19,
        userId: 4,
        review: "Wonderful stay at the Red Door Studio. The place was clean and comfortable, and the mountain view was amazing. Close to everything in El Paso.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 19,
        userId: 1,
        review: "The Red Door Studio was a great find in El Paso. Clean, cozy, and convenient location. The mountain view was a nice touch. Definitely recommend!",
        cleanliness: 5,
        communication: 5,
        checkin: 1,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 19,
        userId: 6,
        review: "Amazing stay at the Red Door Studio. Clean, comfortable, and close to everything. The mountain view was stunning. Highly recommend this place!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 19,
        userId: 7,
        review: "Red Door Studio was the perfect base for our El Paso visit. Comfortable, clean, and centrally located. The mountain view was a lovely bonus.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 20,
        userId: 1,
        review: "We had an amazing time at the lakefront home! The game room, dock, and beautiful scenery made for a memorable stay. Would definitely return.",
        cleanliness: 5,
        communication: 4,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 20,
        userId: 2,
        review: "The lakefront home was a dream come true! We enjoyed the dock, game room, and the stunning views. Perfect for a family getaway.",
        cleanliness: 4,
        communication: 5,
        checkin: 4,
        accuracy: 5,
        location: 5,
        value: 4,
      },
      {
        spotId: 20,
        userId: 3,
        review: "Beautiful location and a comfortable home. We loved the game room and easy access to the lake. A fantastic experience overall!",
        cleanliness: 4,
        communication: 4,
        checkin: 5,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 20,
        userId: 8,
        review: "The lakefront home was perfect for our vacation. Enjoyed the game room and the dock. Beautiful scenery and a great place to unwind.",
        cleanliness: 5,
        communication: 3,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 20,
        userId: 5,
        review: "We loved our stay at this lakefront home. The game room was a hit and the private dock provided endless fun. The views were breathtaking!",
        cleanliness: 4,
        communication: 5,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 20,
        userId: 6,
        review: "An amazing experience at this lakefront home! The game room was perfect for rainy days and the dock was great for sunny ones. Highly recommended.",
        cleanliness: 5,
        communication: 5,
        checkin: 3,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 20,
        userId: 7,
        review: "The lakefront home was everything we could have asked for. Great game room, dock, and views. We had a fantastic time!",
        cleanliness: 5,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 21,
        userId: 1,
        review: "This lake house was the perfect getaway for our family. With 6 bedrooms and close to parks, we had a fantastic time!",
        cleanliness: 5,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 21,
        userId: 2,
        review: "The lake house was lovely, and the proximity to Kohler-Andrae State Park was perfect. We enjoyed our stay.",
        cleanliness: 4,
        communication: 4,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 21,
        userId: 3,
        review: "A beautiful lakefront property with plenty of space for our group. We loved the beach and nearby attractions.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 4,
        location: 5,
        value: 5,
      },
      {
        spotId: 21,
        userId: 4,
        review: "Great location near the lake and state park. The house had everything we needed and was very comfortable.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 21,
        userId: 5,
        review: "The lake house was spacious and had everything we needed. Great location for exploring the nearby state park.",
        cleanliness: 5,
        communication: 3,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 21,
        userId: 6,
        review: "We enjoyed our stay at the lake house. It had plenty of room and was close to the state park and Sheboygan.",
        cleanliness: 4,
        communication: 5,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      {
        spotId: 21,
        userId: 7,
        review: "A wonderful lakefront property with lots of space. We loved the private beach and the peaceful atmosphere.",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 22,
        userId: 1,
        review: "The cabin had a stunning lake view and was a great base for exploring Olympic National Park. We loved our stay!",
        cleanliness: 5,
        communication: 5,
        checkin: 5,
        accuracy: 5,
        location: 5,
        value: 5,
      },
      {
        spotId: 22,
        userId: 2,
        review: "Beautiful cabin with amazing views of Lake Cushman. We enjoyed the game room and proximity to the national park.",
        cleanliness: 4,
        communication: 4,
        checkin: 4,
        accuracy: 4,
        location: 5,
        value: 4,
      },
      { spotId: 22, userId: 3, review: "Incredible location and comfortable accommodations", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 4 },
      { spotId: 22, userId: 4, review: "Breathtaking lake view and beautiful cabin", cleanliness: 4, communication: 3, checkin: 5, accuracy: 5, location: 5, value: 4 },
      { spotId: 22, userId: 5, review: "An idyllic spot for a weekend getaway", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 22, userId: 8, review: "Gorgeous views and cozy living spaces", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 22, userId: 7, review: "A beautiful cabin in a stunning setting", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 23, userId: 1, review: "Perfect family getaway with amazing views", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 23, userId: 2, review: "Great spot for a pet-friendly vacation in nature", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 23, userId: 3, review: "Lovely cabin with fantastic amenities", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 23, userId: 4, review: "Beautiful lake and mountain views from the cabin", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 23, userId: 5, review: "Wonderful location for a family vacation in nature", cleanliness: 5, communication: 4, checkin: 2, accuracy: 5, location: 5, value: 5 },
      { spotId: 23, userId: 6, review: "Great spot for outdoor enthusiasts with pets", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 23, userId: 8, review: "Highly recommended for a relaxing family vacation", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 24, userId: 1, review: "An unforgettable stay in a charming treehouse with amazing views", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 24, userId: 2, review: "A cozy and unique experience in the heart of nature", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 24, userId: 3, review: "The perfect romantic getaway with breathtaking views", cleanliness: 2, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 24, userId: 4, review: "A one-of-a-kind experience in a charming treehouse", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 24, userId: 5, review: "Beautiful views and a cozy atmosphere make this the perfect retreat", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5},
      { spotId: 24, userId: 6, review: "A unique and unforgettable stay in a charming treehouse", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 24, userId: 7, review: "A magical experience in a beautiful location", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 25, userId: 8, review: "Stunning views of the Empire State building!", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 25, userId: 2, review: "Amazing apartment with everything you need for a great stay", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 25, userId: 3, review: "Incredible location with easy access to all the sights", cleanliness: 5, communication: 3, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 25, userId: 4, review: "Beautiful apartment with fantastic skyline views", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 25, userId: 5, review: "Perfect spot for exploring Manhattan and beyond", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 25, userId: 6, review: "A comfortable and stylish apartment with great amenities", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 25, userId: 7, review: "Highly recommended for a New York City stay", cleanliness: 4, communication: 5, checkin: 1, accuracy: 5, location: 5, value: 5 },
      { spotId: 25, userId: 3, review: "Comfortable and spacious townhome with great views", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 25, userId: 1, review: "Amazing property with a great view of downtown", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 26, userId: 3, review: "Perfect spot for a Music City vacation with friends", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 26, userId: 4, review: "Fantastic location and beautiful property", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 26, userId: 5, review: "Great spot for a Music City getaway with friends and pets", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 26, userId: 6, review: "Highly recommended for a Nashville vacation", cleanliness: 5, communication: 2, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 26, userId: 7, review: "A beautiful and comfortable townhome with great amenities", cleanliness: 3, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 26, userId: 8, review: "Fantastic views and a perfect location for a Nashville stay", cleanliness: 5, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 26, userId: 1, review: "A hidden gem in the heart of the city", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 27, userId: 2, review: "Beautiful and unique property with great amenities", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 27, userId: 4, review: "A perfect spot for a New York City stay with pets", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 27, userId: 8, review: "Comfortable and stylish with great features like a sauna", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 27, userId: 5, review: "Fantastic location and beautiful interior design", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 27, userId: 6, review: "A hidden oasis in the middle of the city", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 27, userId: 7, review: "Highly recommended for a New York City vacation", cleanliness: 4, communication: 1, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 27, userId: 1, review: "Cozy and welcoming apartment with great city views", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 28, userId: 2, review: "Perfect location for exploring Boston", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 4 },
      { spotId: 28, userId: 3, review: "A spacious and comfortable apartment with all the amenities", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 28, userId: 1, review: "Fantastic spot for a Boston getaway with friends and pets", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 28, userId: 5, review: "Great location and beautiful apartment", cleanliness: 4, communication: 5, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 28, userId: 6, review: "Highly recommended for a Boston trip", cleanliness: 5, communication: 4, checkin: 5, accuracy: 5, location: 5, value: 5 },
      { spotId: 28, userId: 7, review: "Spacious and clean with everything you need for a comfortable stay", cleanliness: 5, communication: 5, checkin: 4, accuracy: 5, location: 5, value: 5 },
      { spotId: 28, userId: 8, review: "Fantastic value and location for a Boston vacation", cleanliness: 4, communication: 5, checkin: 3, accuracy: 5, location: 5, value: 5 },
    ], {})
  },

  async down(queryInterface, Sequelize) {
    options.tableName = "Reviews";
    const Op = Sequelize.Op;
    // return queryInterface.bulkDelete(options, {
    //   id: { [Op.in]: [1, 2, 3, 4, 5, 6, 7, 8] }
    // }, {})
    return queryInterface.bulkDelete(options, null, {});
  }
};
